In [1]:
import torch
import numpy as np

In [2]:
a = np.array([1, 2])
b = np.array([3, 4])
c = a + b

In [3]:
c

array([4, 6])

In [4]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = a + b

In [5]:
c

tensor([4, 6])

In [6]:
torch.FloatTensor([[1, 2], [3, 4]])

tensor([[1., 2.],
        [3., 4.]])

In [7]:
torch.tensor([[1, 2], [3, 4]], dtype=bool)

tensor([[True, True],
        [True, True]])

In [8]:
torch.rand(3, 2)

tensor([[0.5948, 0.6938],
        [0.6748, 0.6939],
        [0.4644, 0.8335]])

In [9]:
x = torch.tensor([[1, 2], [3, 4]])
x.t()

tensor([[1, 3],
        [2, 4]])

In [10]:
y = torch.tensor([[1, 3], [5, 6]])
z = x.add(y)

In [11]:
z

tensor([[ 2,  5],
        [ 8, 10]])

### Autograd

In [12]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [13]:
device

device(type='cpu')

In [14]:
x = torch.tensor([[1, 3], [4, 5]])
x.to(device)


tensor([[1, 3],
        [4, 5]])